name: Tests

on:
    push:
        branches: ['main']
    pull_request:
        branches: ['main']

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [18.x, 20.x]

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - run: npm ci
            - run: npm run build --if-present
            - run: npm test
            - name: Upload coverage to Codecov
              uses: codecov/codecov-action@v4
              with:
                directory: ./coverage/reports/
                fail_ci_if_error: true
                files: ./coverage1.xml,./coverage2.xml,!./cache
                flags: unittests
                name: codecov-umbrella
                token: ${{ secrets.CODECOV_TOKEN }}
                verbose: true
